
package publicadores;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "publicadorTroesmaService", targetNamespace = "http://publicadores/", wsdlLocation = "http://localhost:1981/publicado?wsdl")
public class PublicadorTroesmaService
    extends Service
{

    private final static URL PUBLICADORTROESMASERVICE_WSDL_LOCATION;
    private final static WebServiceException PUBLICADORTROESMASERVICE_EXCEPTION;
    private final static QName PUBLICADORTROESMASERVICE_QNAME = new QName("http://publicadores/", "publicadorTroesmaService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:1981/publicado?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PUBLICADORTROESMASERVICE_WSDL_LOCATION = url;
        PUBLICADORTROESMASERVICE_EXCEPTION = e;
    }

    public PublicadorTroesmaService() {
        super(__getWsdlLocation(), PUBLICADORTROESMASERVICE_QNAME);
    }

    public PublicadorTroesmaService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PUBLICADORTROESMASERVICE_QNAME, features);
    }

    public PublicadorTroesmaService(URL wsdlLocation) {
        super(wsdlLocation, PUBLICADORTROESMASERVICE_QNAME);
    }

    public PublicadorTroesmaService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PUBLICADORTROESMASERVICE_QNAME, features);
    }

    public PublicadorTroesmaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PublicadorTroesmaService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PublicadorTroesma
     */
    @WebEndpoint(name = "publicadorTroesmaPort")
    public PublicadorTroesma getPublicadorTroesmaPort() {
        return super.getPort(new QName("http://publicadores/", "publicadorTroesmaPort"), PublicadorTroesma.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PublicadorTroesma
     */
    @WebEndpoint(name = "publicadorTroesmaPort")
    public PublicadorTroesma getPublicadorTroesmaPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://publicadores/", "publicadorTroesmaPort"), PublicadorTroesma.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PUBLICADORTROESMASERVICE_EXCEPTION!= null) {
            throw PUBLICADORTROESMASERVICE_EXCEPTION;
        }
        return PUBLICADORTROESMASERVICE_WSDL_LOCATION;
    }

}
