
package publicadores;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "publicadorTroesma", targetNamespace = "http://publicadores/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PublicadorTroesma {


    /**
     * 
     * @return
     *     returns publicadores.DtActividadArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/publicadorTroesma/getRankingActividadesRequest", output = "http://publicadores/publicadorTroesma/getRankingActividadesResponse")
    public DtActividadArray getRankingActividades();

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/publicadorTroesma/existeActividadRequest", output = "http://publicadores/publicadorTroesma/existeActividadResponse")
    public boolean existeActividad(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicadores.DtActividad
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/publicadorTroesma/getDtActividadRequest", output = "http://publicadores/publicadorTroesma/getDtActividadResponse")
    public DtActividad getDtActividad(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicadores.DtSocio
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/publicadorTroesma/getDtSocioRequest", output = "http://publicadores/publicadorTroesma/getDtSocioResponse")
    public DtSocio getDtSocio(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/publicadorTroesma/existeUsuarioRequest", output = "http://publicadores/publicadorTroesma/existeUsuarioResponse")
    public boolean existeUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/publicadorTroesma/esSocioRequest", output = "http://publicadores/publicadorTroesma/esSocioResponse")
    public boolean esSocio(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicadores.DtProfesor
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/publicadorTroesma/getDtProfesorRequest", output = "http://publicadores/publicadorTroesma/getDtProfesorResponse")
    public DtProfesor getDtProfesor(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/publicadorTroesma/esContrasenaRequest", output = "http://publicadores/publicadorTroesma/esContrasenaResponse")
    public boolean esContrasena(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

}
